/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Category = IDL.Variant({
  'housekeeping' : IDL.Null,
  'plumbing' : IDL.Null,
  'electrical' : IDL.Null,
  'carpentry' : IDL.Null,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'purchaseDate' : Time,
  'supplier' : IDL.Text,
  'cost' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : Category,
  'location' : IDL.Text,
});
export const IssueRecord = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'issuedAt' : Time,
  'issuedBy' : IDL.Principal,
  'issuedTo' : IDL.Text,
  'department' : IDL.Text,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ItemRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'itemId' : IDL.Nat,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'department' : IDL.Text,
  'requestedBy' : IDL.Principal,
  'resolvedAt' : IDL.Opt(Time),
  'resolvedBy' : IDL.Opt(IDL.Principal),
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const CategorySummary = IDL.Record({
  'itemCount' : IDL.Nat,
  'category' : Category,
  'totalQuantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInventoryItem' : IDL.Func([InventoryItem], [IDL.Nat], []),
  'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllIssueRecords' : IDL.Func([], [IDL.Vec(IssueRecord)], ['query']),
  'getAllItemRequests' : IDL.Func([], [IDL.Vec(ItemRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategorySummary' : IDL.Func([], [IDL.Vec(CategorySummary)], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Nat], [IDL.Opt(InventoryItem)], ['query']),
  'getIssueRecordsByItem' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IssueRecord)],
      ['query'],
    ),
  'getItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(ItemRequest)], ['query']),
  'getRequestsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ItemRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'rejectRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitItemRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateInventoryItem' : IDL.Func([IDL.Nat, InventoryItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'housekeeping' : IDL.Null,
    'plumbing' : IDL.Null,
    'electrical' : IDL.Null,
    'carpentry' : IDL.Null,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'purchaseDate' : Time,
    'supplier' : IDL.Text,
    'cost' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : Category,
    'location' : IDL.Text,
  });
  const IssueRecord = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'issuedAt' : Time,
    'issuedBy' : IDL.Principal,
    'issuedTo' : IDL.Text,
    'department' : IDL.Text,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ItemRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'itemId' : IDL.Nat,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'department' : IDL.Text,
    'requestedBy' : IDL.Principal,
    'resolvedAt' : IDL.Opt(Time),
    'resolvedBy' : IDL.Opt(IDL.Principal),
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const CategorySummary = IDL.Record({
    'itemCount' : IDL.Nat,
    'category' : Category,
    'totalQuantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInventoryItem' : IDL.Func([InventoryItem], [IDL.Nat], []),
    'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllIssueRecords' : IDL.Func([], [IDL.Vec(IssueRecord)], ['query']),
    'getAllItemRequests' : IDL.Func([], [IDL.Vec(ItemRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategorySummary' : IDL.Func([], [IDL.Vec(CategorySummary)], ['query']),
    'getInventoryItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InventoryItem)],
        ['query'],
      ),
    'getIssueRecordsByItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IssueRecord)],
        ['query'],
      ),
    'getItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(ItemRequest)], ['query']),
    'getRequestsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ItemRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'rejectRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitItemRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateInventoryItem' : IDL.Func([IDL.Nat, InventoryItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };