/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'housekeeping' : null } |
  { 'plumbing' : null } |
  { 'electrical' : null } |
  { 'carpentry' : null };
export interface CategorySummary {
  'itemCount' : bigint,
  'category' : Category,
  'totalQuantity' : bigint,
}
export interface InventoryItem {
  'id' : bigint,
  'lowStockThreshold' : bigint,
  'purchaseDate' : Time,
  'supplier' : string,
  'cost' : number,
  'name' : string,
  'unit' : string,
  'quantity' : bigint,
  'category' : Category,
  'location' : string,
}
export interface IssueRecord {
  'id' : bigint,
  'itemId' : bigint,
  'notes' : string,
  'quantity' : bigint,
  'issuedAt' : Time,
  'issuedBy' : Principal,
  'issuedTo' : string,
  'department' : string,
}
export interface ItemRequest {
  'id' : bigint,
  'status' : RequestStatus,
  'itemId' : bigint,
  'createdAt' : Time,
  'notes' : string,
  'quantity' : bigint,
  'department' : string,
  'requestedBy' : Principal,
  'resolvedAt' : [] | [Time],
  'resolvedBy' : [] | [Principal],
  'reason' : string,
}
export type RequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'department' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveRequest' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInventoryItem' : ActorMethod<[InventoryItem], bigint>,
  'deleteInventoryItem' : ActorMethod<[bigint], undefined>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllIssueRecords' : ActorMethod<[], Array<IssueRecord>>,
  'getAllItemRequests' : ActorMethod<[], Array<ItemRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategorySummary' : ActorMethod<[], Array<CategorySummary>>,
  'getInventoryItem' : ActorMethod<[bigint], [] | [InventoryItem]>,
  'getIssueRecordsByItem' : ActorMethod<[bigint], Array<IssueRecord>>,
  'getItemsByCategory' : ActorMethod<[Category], Array<InventoryItem>>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getPendingRequests' : ActorMethod<[], Array<ItemRequest>>,
  'getRequestsByUser' : ActorMethod<[Principal], Array<ItemRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueItem' : ActorMethod<[bigint, string, string, bigint, string], bigint>,
  'rejectRequest' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitItemRequest' : ActorMethod<[bigint, string, bigint, string], bigint>,
  'updateInventoryItem' : ActorMethod<[bigint, InventoryItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];